version: 1

update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'weekly'
    target_branch: 'master'
    default_reviewers:
      - 'tyankatsu0105'
    default_assignees:
      - 'tyankatsu0105'
    default_labels:
      - 'ğŸ¤–dependencies'